/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/

package main

import "fmt"

func main() {
	fmt.Println(evenFibonacciSum(4_000_000))
}

func evenFibonacciSum(limit int) int {
	a, b := 1, 2
	sum := 2

	for {
		next := a + b
		if next > limit {
			break
		}

		if next%2 == 0 {
			sum += next
		}

		a, b = b, next
	}

	return sum
}

//4613732
