/*
<p>The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$</p>
<p>Let us list the factors of the first seven triangle numbers:</p>
$$\begin{align}
\mathbf 1 &amp;\colon 1\\
\mathbf 3 &amp;\colon 1,3\\
\mathbf 6 &amp;\colon 1,2,3,6\\
\mathbf{10} &amp;\colon 1,2,5,10\\
\mathbf{15} &amp;\colon 1,3,5,15\\
\mathbf{21} &amp;\colon 1,3,7,21\\
\mathbf{28} &amp;\colon 1,2,4,7,14,28
\end{align}$$
<p>We can see that $28$ is the first triangle number to have over five divisors.</p>
<p>What is the value of the first triangle number to have over five hundred divisors?</p>
*/

package main

import (
	"fmt"
	"math"
)

func main() {

	for n := 1; ; n++ {
		triangularNumber := getTriangularNumber(n)

		totalNumberOfDivisors := getNumberOfDivisors(triangularNumber)

		if totalNumberOfDivisors > 500 {
			fmt.Println(triangularNumber)
			break
		}

	}

}

func getTriangularNumber(n int) int {
	return n * (n + 1) / 2
}

func primesTillN(limit int) []int {
	prime := make([]bool, limit)

	for i := 2; i < limit; i++ {
		prime[i] = true
	}

	for p := 2; p*p < limit; p++ {

		if prime[p] {
			for multiple := p * p; multiple < limit; multiple += p {
				prime[multiple] = false
			}
		}
	}

	finalPrimes := []int{}

	for index, value := range prime {
		if value {
			finalPrimes = append(finalPrimes, index)
		}
	}

	return finalPrimes
}

func getNumberOfDivisors(n int) int {

	primes := primesTillN(int(math.Sqrt(float64(n))) + 1)

	totalNumberOfDivisors := 1
	for _, p := range primes {

		count := 0
		if n%p == 0 {

			for n%p == 0 {

				n /= p

				count++
			}

			totalNumberOfDivisors = totalNumberOfDivisors * (count + 1)
		}

	}

	return totalNumberOfDivisors
}

// 76576500
